name: MinecraftGlobalAnalytics
version: 1.0
main: global.minecraft.MinecraftGlobalAnalytics.Main
authors: [ Iapetus11, trustedmercury ]
description: The official plugin for statistics on https://minecraft.global
